-- -------------------------------------------------------------
-- 
-- File Name: Freq_comparator_TX\hdlsrc\FrequencyComparator_Tx\SignalGen_ip_src_Signal_Generation_pkg.vhd
-- Created: 2020-05-30 19:24:02
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE SignalGen_ip_src_Signal_Generation_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
  TYPE vector_of_unsigned4 IS ARRAY (NATURAL RANGE <>) OF unsigned(3 DOWNTO 0);
END SignalGen_ip_src_Signal_Generation_pkg;

