ASFLAGS_ADDITIONAL = 
TARGET_SYSROOT = C:/PROGRA~3/MATLAB/SUPPOR~1/R2020a/3P778C~1.INS/ZYNQLI~1.INS/SYSROO~1
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2020a/toolbox/target/SUPPOR~1/zynq
STACK_SIZE = 64
