open_system('FrequencyComparator_Tx');
open_system('gm_FrequencyComparator_Tx');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FrequencyComparator_Tx/Signal Generation/Sine Wave', 'user2');
annotate_port('gm_FrequencyComparator_Tx/Signal Generation/Sine Wave', 0, 1, 'Block not characterized');
hilite_system('FrequencyComparator_Tx/Signal Generation/Sine Wave', 'user2');
annotate_port('FrequencyComparator_Tx/Signal Generation/Sine Wave', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_FrequencyComparator_Tx/Signal Generation/Sine Wave', 'user2');
annotate_port('gm_FrequencyComparator_Tx/Signal Generation/Sine Wave', 0, 1, 'Block not characterized');
hilite_system('FrequencyComparator_Tx/Signal Generation/Sine Wave', 'user2');
annotate_port('FrequencyComparator_Tx/Signal Generation/Sine Wave', 0, 1, 'Block not characterized');
