-- -------------------------------------------------------------
-- 
-- File Name: Freq_comparator_TX\hdlsrc\FrequencyComparator_Tx\SignalGen_ip_src_Sine_Wave.vhd
-- Created: 2020-05-30 19:24:02
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SignalGen_ip_src_Sine_Wave
-- Source Path: FrequencyComparator_Tx/Signal Generation/Sine Wave
-- Hierarchy Level: 1
-- 
-- Sine Wave
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.SignalGen_ip_src_Signal_Generation_pkg.ALL;

ENTITY SignalGen_ip_src_Sine_Wave IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Sine_Wave_out1_re                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        Sine_Wave_out1_im                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END SignalGen_ip_src_Sine_Wave;


ARCHITECTURE rtl OF SignalGen_ip_src_Sine_Wave IS

  -- Constants
  CONSTANT Lookup_Table1_table_data       : vector_of_signed16(0 TO 9) := 
    (to_signed(16#4000#, 16), to_signed(16#33C7#, 16), to_signed(16#13C7#, 16), to_signed(-16#13C7#, 16),
     to_signed(-16#33C7#, 16), to_signed(-16#4000#, 16), to_signed(-16#33C7#, 16), to_signed(-16#13C7#, 16),
     to_signed(16#13C7#, 16), to_signed(16#33C7#, 16));  -- sfix16 [10]
  CONSTANT Lookup_Table2_table_data       : vector_of_signed16(0 TO 9) := 
    (to_signed(16#0000#, 16), to_signed(16#259E#, 16), to_signed(16#3CDE#, 16), to_signed(16#3CDE#, 16),
     to_signed(16#259E#, 16), to_signed(16#0000#, 16), to_signed(-16#259E#, 16), to_signed(-16#3CDE#, 16),
     to_signed(-16#3CDE#, 16), to_signed(-16#259E#, 16));  -- sfix16 [10]

  -- Signals
  SIGNAL address_cnt1                     : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Lookup_Table1_k                  : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL lut1out_real1                    : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Lookup_Table2_k                  : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL lut1out_img1                     : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 9
  Sine_Wave_addrcnt_temp_process1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      address_cnt1 <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF address_cnt1 >= to_unsigned(16#9#, 4) THEN 
          address_cnt1 <= to_unsigned(16#0#, 4);
        ELSE 
          address_cnt1 <= address_cnt1 + to_unsigned(16#1#, 4);
        END IF;
      END IF;
    END IF;
  END PROCESS Sine_Wave_addrcnt_temp_process1_process;


  
  Lookup_Table1_k <= to_unsigned(16#0#, 4) WHEN address_cnt1 = to_unsigned(16#0#, 4) ELSE
      to_unsigned(16#9#, 4) WHEN address_cnt1 >= to_unsigned(16#9#, 4) ELSE
      address_cnt1;
  lut1out_real1 <= Lookup_Table1_table_data(to_integer(Lookup_Table1_k));

  Sine_Wave_out1_re <= std_logic_vector(lut1out_real1);

  
  Lookup_Table2_k <= to_unsigned(16#0#, 4) WHEN address_cnt1 = to_unsigned(16#0#, 4) ELSE
      to_unsigned(16#9#, 4) WHEN address_cnt1 >= to_unsigned(16#9#, 4) ELSE
      address_cnt1;
  lut1out_img1 <= Lookup_Table2_table_data(to_integer(Lookup_Table2_k));

  Sine_Wave_out1_im <= std_logic_vector(lut1out_img1);

END rtl;

