-- ------------------------------------------------------------
-- 
-- File Name: PN_generator_TX\hdlsrc\PN_generatorV2\PN_genera_ip_src_FIR_Interpolation
-- Created: 2020-05-30 19:56:34
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- ------------------------------------------------------------
-- 
-- 
-- ------------------------------------------------------------
-- 
-- Module: PN_genera_ip_src_FIR_Interpolation
-- Source Path: /PN_genera_ip_src_FIR_Interpolation
-- 
-- ------------------------------------------------------------
-- 
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- Multipliers           : 17


LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY PN_genera_ip_src_FIR_Interpolation IS
   PORT( clk                             :   IN    std_logic; 
         enb_1_1_1                       :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         PN_genera_ip_src_FIR_Interpolation_in:   IN    std_logic_vector(15 DOWNTO 0); -- sfix16_En15
         PN_genera_ip_src_FIR_Interpolation_out:   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
         );

END PN_genera_ip_src_FIR_Interpolation;


----------------------------------------------------------------
--Module Architecture: PN_genera_ip_src_FIR_Interpolation
----------------------------------------------------------------
ARCHITECTURE rtl OF PN_genera_ip_src_FIR_Interpolation IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(15 DOWNTO 0); -- sfix16_En15
  -- Constants
  CONSTANT coeffphase1_1                  : signed(15 DOWNTO 0) := to_signed(-41, 16); -- sfix16_En15
  CONSTANT coeffphase1_2                  : signed(15 DOWNTO 0) := to_signed(4, 16); -- sfix16_En15
  CONSTANT coeffphase1_3                  : signed(15 DOWNTO 0) := to_signed(73, 16); -- sfix16_En15
  CONSTANT coeffphase1_4                  : signed(15 DOWNTO 0) := to_signed(-11, 16); -- sfix16_En15
  CONSTANT coeffphase1_5                  : signed(15 DOWNTO 0) := to_signed(-166, 16); -- sfix16_En15
  CONSTANT coeffphase1_6                  : signed(15 DOWNTO 0) := to_signed(50, 16); -- sfix16_En15
  CONSTANT coeffphase1_7                  : signed(15 DOWNTO 0) := to_signed(695, 16); -- sfix16_En15
  CONSTANT coeffphase1_8                  : signed(15 DOWNTO 0) := to_signed(-1738, 16); -- sfix16_En15
  CONSTANT coeffphase1_9                  : signed(15 DOWNTO 0) := to_signed(18623, 16); -- sfix16_En15
  CONSTANT coeffphase1_10                 : signed(15 DOWNTO 0) := to_signed(-1738, 16); -- sfix16_En15
  CONSTANT coeffphase1_11                 : signed(15 DOWNTO 0) := to_signed(695, 16); -- sfix16_En15
  CONSTANT coeffphase1_12                 : signed(15 DOWNTO 0) := to_signed(50, 16); -- sfix16_En15
  CONSTANT coeffphase1_13                 : signed(15 DOWNTO 0) := to_signed(-166, 16); -- sfix16_En15
  CONSTANT coeffphase1_14                 : signed(15 DOWNTO 0) := to_signed(-11, 16); -- sfix16_En15
  CONSTANT coeffphase1_15                 : signed(15 DOWNTO 0) := to_signed(73, 16); -- sfix16_En15
  CONSTANT coeffphase1_16                 : signed(15 DOWNTO 0) := to_signed(4, 16); -- sfix16_En15
  CONSTANT coeffphase1_17                 : signed(15 DOWNTO 0) := to_signed(-41, 16); -- sfix16_En15
  CONSTANT coeffphase2_1                  : signed(15 DOWNTO 0) := to_signed(-40, 16); -- sfix16_En15
  CONSTANT coeffphase2_2                  : signed(15 DOWNTO 0) := to_signed(-12, 16); -- sfix16_En15
  CONSTANT coeffphase2_3                  : signed(15 DOWNTO 0) := to_signed(71, 16); -- sfix16_En15
  CONSTANT coeffphase2_4                  : signed(15 DOWNTO 0) := to_signed(20, 16); -- sfix16_En15
  CONSTANT coeffphase2_5                  : signed(15 DOWNTO 0) := to_signed(-161, 16); -- sfix16_En15
  CONSTANT coeffphase2_6                  : signed(15 DOWNTO 0) := to_signed(-38, 16); -- sfix16_En15
  CONSTANT coeffphase2_7                  : signed(15 DOWNTO 0) := to_signed(693, 16); -- sfix16_En15
  CONSTANT coeffphase2_8                  : signed(15 DOWNTO 0) := to_signed(-997, 16); -- sfix16_En15
  CONSTANT coeffphase2_9                  : signed(15 DOWNTO 0) := to_signed(18449, 16); -- sfix16_En15
  CONSTANT coeffphase2_10                 : signed(15 DOWNTO 0) := to_signed(-2251, 16); -- sfix16_En15
  CONSTANT coeffphase2_11                 : signed(15 DOWNTO 0) := to_signed(639, 16); -- sfix16_En15
  CONSTANT coeffphase2_12                 : signed(15 DOWNTO 0) := to_signed(129, 16); -- sfix16_En15
  CONSTANT coeffphase2_13                 : signed(15 DOWNTO 0) := to_signed(-155, 16); -- sfix16_En15
  CONSTANT coeffphase2_14                 : signed(15 DOWNTO 0) := to_signed(-40, 16); -- sfix16_En15
  CONSTANT coeffphase2_15                 : signed(15 DOWNTO 0) := to_signed(69, 16); -- sfix16_En15
  CONSTANT coeffphase2_16                 : signed(15 DOWNTO 0) := to_signed(19, 16); -- sfix16_En15
  CONSTANT coeffphase2_17                 : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase3_1                  : signed(15 DOWNTO 0) := to_signed(-35, 16); -- sfix16_En15
  CONSTANT coeffphase3_2                  : signed(15 DOWNTO 0) := to_signed(-27, 16); -- sfix16_En15
  CONSTANT coeffphase3_3                  : signed(15 DOWNTO 0) := to_signed(62, 16); -- sfix16_En15
  CONSTANT coeffphase3_4                  : signed(15 DOWNTO 0) := to_signed(50, 16); -- sfix16_En15
  CONSTANT coeffphase3_5                  : signed(15 DOWNTO 0) := to_signed(-142, 16); -- sfix16_En15
  CONSTANT coeffphase3_6                  : signed(15 DOWNTO 0) := to_signed(-125, 16); -- sfix16_En15
  CONSTANT coeffphase3_7                  : signed(15 DOWNTO 0) := to_signed(622, 16); -- sfix16_En15
  CONSTANT coeffphase3_8                  : signed(15 DOWNTO 0) := to_signed(-25, 16); -- sfix16_En15
  CONSTANT coeffphase3_9                  : signed(15 DOWNTO 0) := to_signed(17933, 16); -- sfix16_En15
  CONSTANT coeffphase3_10                 : signed(15 DOWNTO 0) := to_signed(-2546, 16); -- sfix16_En15
  CONSTANT coeffphase3_11                 : signed(15 DOWNTO 0) := to_signed(536, 16); -- sfix16_En15
  CONSTANT coeffphase3_12                 : signed(15 DOWNTO 0) := to_signed(195, 16); -- sfix16_En15
  CONSTANT coeffphase3_13                 : signed(15 DOWNTO 0) := to_signed(-133, 16); -- sfix16_En15
  CONSTANT coeffphase3_14                 : signed(15 DOWNTO 0) := to_signed(-65, 16); -- sfix16_En15
  CONSTANT coeffphase3_15                 : signed(15 DOWNTO 0) := to_signed(59, 16); -- sfix16_En15
  CONSTANT coeffphase3_16                 : signed(15 DOWNTO 0) := to_signed(32, 16); -- sfix16_En15
  CONSTANT coeffphase3_17                 : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase4_1                  : signed(15 DOWNTO 0) := to_signed(-26, 16); -- sfix16_En15
  CONSTANT coeffphase4_2                  : signed(15 DOWNTO 0) := to_signed(-40, 16); -- sfix16_En15
  CONSTANT coeffphase4_3                  : signed(15 DOWNTO 0) := to_signed(47, 16); -- sfix16_En15
  CONSTANT coeffphase4_4                  : signed(15 DOWNTO 0) := to_signed(77, 16); -- sfix16_En15
  CONSTANT coeffphase4_5                  : signed(15 DOWNTO 0) := to_signed(-109, 16); -- sfix16_En15
  CONSTANT coeffphase4_6                  : signed(15 DOWNTO 0) := to_signed(-205, 16); -- sfix16_En15
  CONSTANT coeffphase4_7                  : signed(15 DOWNTO 0) := to_signed(476, 16); -- sfix16_En15
  CONSTANT coeffphase4_8                  : signed(15 DOWNTO 0) := to_signed(1171, 16); -- sfix16_En15
  CONSTANT coeffphase4_9                  : signed(15 DOWNTO 0) := to_signed(17095, 16); -- sfix16_En15
  CONSTANT coeffphase4_10                 : signed(15 DOWNTO 0) := to_signed(-2643, 16); -- sfix16_En15
  CONSTANT coeffphase4_11                 : signed(15 DOWNTO 0) := to_signed(403, 16); -- sfix16_En15
  CONSTANT coeffphase4_12                 : signed(15 DOWNTO 0) := to_signed(243, 16); -- sfix16_En15
  CONSTANT coeffphase4_13                 : signed(15 DOWNTO 0) := to_signed(-101, 16); -- sfix16_En15
  CONSTANT coeffphase4_14                 : signed(15 DOWNTO 0) := to_signed(-85, 16); -- sfix16_En15
  CONSTANT coeffphase4_15                 : signed(15 DOWNTO 0) := to_signed(45, 16); -- sfix16_En15
  CONSTANT coeffphase4_16                 : signed(15 DOWNTO 0) := to_signed(43, 16); -- sfix16_En15
  CONSTANT coeffphase4_17                 : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase5_1                  : signed(15 DOWNTO 0) := to_signed(-16, 16); -- sfix16_En15
  CONSTANT coeffphase5_2                  : signed(15 DOWNTO 0) := to_signed(-49, 16); -- sfix16_En15
  CONSTANT coeffphase5_3                  : signed(15 DOWNTO 0) := to_signed(28, 16); -- sfix16_En15
  CONSTANT coeffphase5_4                  : signed(15 DOWNTO 0) := to_signed(97, 16); -- sfix16_En15
  CONSTANT coeffphase5_5                  : signed(15 DOWNTO 0) := to_signed(-63, 16); -- sfix16_En15
  CONSTANT coeffphase5_6                  : signed(15 DOWNTO 0) := to_signed(-270, 16); -- sfix16_En15
  CONSTANT coeffphase5_7                  : signed(15 DOWNTO 0) := to_signed(253, 16); -- sfix16_En15
  CONSTANT coeffphase5_8                  : signed(15 DOWNTO 0) := to_signed(2570, 16); -- sfix16_En15
  CONSTANT coeffphase5_9                  : signed(15 DOWNTO 0) := to_signed(15966, 16); -- sfix16_En15
  CONSTANT coeffphase5_10                 : signed(15 DOWNTO 0) := to_signed(-2570, 16); -- sfix16_En15
  CONSTANT coeffphase5_11                 : signed(15 DOWNTO 0) := to_signed(253, 16); -- sfix16_En15
  CONSTANT coeffphase5_12                 : signed(15 DOWNTO 0) := to_signed(270, 16); -- sfix16_En15
  CONSTANT coeffphase5_13                 : signed(15 DOWNTO 0) := to_signed(-63, 16); -- sfix16_En15
  CONSTANT coeffphase5_14                 : signed(15 DOWNTO 0) := to_signed(-97, 16); -- sfix16_En15
  CONSTANT coeffphase5_15                 : signed(15 DOWNTO 0) := to_signed(28, 16); -- sfix16_En15
  CONSTANT coeffphase5_16                 : signed(15 DOWNTO 0) := to_signed(49, 16); -- sfix16_En15
  CONSTANT coeffphase5_17                 : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase6_1                  : signed(15 DOWNTO 0) := to_signed(-3, 16); -- sfix16_En15
  CONSTANT coeffphase6_2                  : signed(15 DOWNTO 0) := to_signed(-54, 16); -- sfix16_En15
  CONSTANT coeffphase6_3                  : signed(15 DOWNTO 0) := to_signed(5, 16); -- sfix16_En15
  CONSTANT coeffphase6_4                  : signed(15 DOWNTO 0) := to_signed(108, 16); -- sfix16_En15
  CONSTANT coeffphase6_5                  : signed(15 DOWNTO 0) := to_signed(-7, 16); -- sfix16_En15
  CONSTANT coeffphase6_6                  : signed(15 DOWNTO 0) := to_signed(-311, 16); -- sfix16_En15
  CONSTANT coeffphase6_7                  : signed(15 DOWNTO 0) := to_signed(-42, 16); -- sfix16_En15
  CONSTANT coeffphase6_8                  : signed(15 DOWNTO 0) := to_signed(4143, 16); -- sfix16_En15
  CONSTANT coeffphase6_9                  : signed(15 DOWNTO 0) := to_signed(14588, 16); -- sfix16_En15
  CONSTANT coeffphase6_10                 : signed(15 DOWNTO 0) := to_signed(-2357, 16); -- sfix16_En15
  CONSTANT coeffphase6_11                 : signed(15 DOWNTO 0) := to_signed(102, 16); -- sfix16_En15
  CONSTANT coeffphase6_12                 : signed(15 DOWNTO 0) := to_signed(274, 16); -- sfix16_En15
  CONSTANT coeffphase6_13                 : signed(15 DOWNTO 0) := to_signed(-22, 16); -- sfix16_En15
  CONSTANT coeffphase6_14                 : signed(15 DOWNTO 0) := to_signed(-101, 16); -- sfix16_En15
  CONSTANT coeffphase6_15                 : signed(15 DOWNTO 0) := to_signed(9, 16); -- sfix16_En15
  CONSTANT coeffphase6_16                 : signed(15 DOWNTO 0) := to_signed(52, 16); -- sfix16_En15
  CONSTANT coeffphase6_17                 : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase7_1                  : signed(15 DOWNTO 0) := to_signed(10, 16); -- sfix16_En15
  CONSTANT coeffphase7_2                  : signed(15 DOWNTO 0) := to_signed(-55, 16); -- sfix16_En15
  CONSTANT coeffphase7_3                  : signed(15 DOWNTO 0) := to_signed(-20, 16); -- sfix16_En15
  CONSTANT coeffphase7_4                  : signed(15 DOWNTO 0) := to_signed(110, 16); -- sfix16_En15
  CONSTANT coeffphase7_5                  : signed(15 DOWNTO 0) := to_signed(55, 16); -- sfix16_En15
  CONSTANT coeffphase7_6                  : signed(15 DOWNTO 0) := to_signed(-323, 16); -- sfix16_En15
  CONSTANT coeffphase7_7                  : signed(15 DOWNTO 0) := to_signed(-399, 16); -- sfix16_En15
  CONSTANT coeffphase7_8                  : signed(15 DOWNTO 0) := to_signed(5852, 16); -- sfix16_En15
  CONSTANT coeffphase7_9                  : signed(15 DOWNTO 0) := to_signed(13009, 16); -- sfix16_En15
  CONSTANT coeffphase7_10                 : signed(15 DOWNTO 0) := to_signed(-2039, 16); -- sfix16_En15
  CONSTANT coeffphase7_11                 : signed(15 DOWNTO 0) := to_signed(-38, 16); -- sfix16_En15
  CONSTANT coeffphase7_12                 : signed(15 DOWNTO 0) := to_signed(258, 16); -- sfix16_En15
  CONSTANT coeffphase7_13                 : signed(15 DOWNTO 0) := to_signed(18, 16); -- sfix16_En15
  CONSTANT coeffphase7_14                 : signed(15 DOWNTO 0) := to_signed(-96, 16); -- sfix16_En15
  CONSTANT coeffphase7_15                 : signed(15 DOWNTO 0) := to_signed(-10, 16); -- sfix16_En15
  CONSTANT coeffphase7_16                 : signed(15 DOWNTO 0) := to_signed(50, 16); -- sfix16_En15
  CONSTANT coeffphase7_17                 : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase8_1                  : signed(15 DOWNTO 0) := to_signed(24, 16); -- sfix16_En15
  CONSTANT coeffphase8_2                  : signed(15 DOWNTO 0) := to_signed(-50, 16); -- sfix16_En15
  CONSTANT coeffphase8_3                  : signed(15 DOWNTO 0) := to_signed(-45, 16); -- sfix16_En15
  CONSTANT coeffphase8_4                  : signed(15 DOWNTO 0) := to_signed(101, 16); -- sfix16_En15
  CONSTANT coeffphase8_5                  : signed(15 DOWNTO 0) := to_signed(117, 16); -- sfix16_En15
  CONSTANT coeffphase8_6                  : signed(15 DOWNTO 0) := to_signed(-302, 16); -- sfix16_En15
  CONSTANT coeffphase8_7                  : signed(15 DOWNTO 0) := to_signed(-802, 16); -- sfix16_En15
  CONSTANT coeffphase8_8                  : signed(15 DOWNTO 0) := to_signed(7649, 16); -- sfix16_En15
  CONSTANT coeffphase8_9                  : signed(15 DOWNTO 0) := to_signed(11287, 16); -- sfix16_En15
  CONSTANT coeffphase8_10                 : signed(15 DOWNTO 0) := to_signed(-1652, 16); -- sfix16_En15
  CONSTANT coeffphase8_11                 : signed(15 DOWNTO 0) := to_signed(-156, 16); -- sfix16_En15
  CONSTANT coeffphase8_12                 : signed(15 DOWNTO 0) := to_signed(224, 16); -- sfix16_En15
  CONSTANT coeffphase8_13                 : signed(15 DOWNTO 0) := to_signed(54, 16); -- sfix16_En15
  CONSTANT coeffphase8_14                 : signed(15 DOWNTO 0) := to_signed(-85, 16); -- sfix16_En15
  CONSTANT coeffphase8_15                 : signed(15 DOWNTO 0) := to_signed(-27, 16); -- sfix16_En15
  CONSTANT coeffphase8_16                 : signed(15 DOWNTO 0) := to_signed(44, 16); -- sfix16_En15
  CONSTANT coeffphase8_17                 : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase9_1                  : signed(15 DOWNTO 0) := to_signed(35, 16); -- sfix16_En15
  CONSTANT coeffphase9_2                  : signed(15 DOWNTO 0) := to_signed(-41, 16); -- sfix16_En15
  CONSTANT coeffphase9_3                  : signed(15 DOWNTO 0) := to_signed(-67, 16); -- sfix16_En15
  CONSTANT coeffphase9_4                  : signed(15 DOWNTO 0) := to_signed(82, 16); -- sfix16_En15
  CONSTANT coeffphase9_5                  : signed(15 DOWNTO 0) := to_signed(176, 16); -- sfix16_En15
  CONSTANT coeffphase9_6                  : signed(15 DOWNTO 0) := to_signed(-246, 16); -- sfix16_En15
  CONSTANT coeffphase9_7                  : signed(15 DOWNTO 0) := to_signed(-1229, 16); -- sfix16_En15
  CONSTANT coeffphase9_8                  : signed(15 DOWNTO 0) := to_signed(9480, 16); -- sfix16_En15
  CONSTANT coeffphase9_9                  : signed(15 DOWNTO 0) := to_signed(9480, 16); -- sfix16_En15
  CONSTANT coeffphase9_10                 : signed(15 DOWNTO 0) := to_signed(-1229, 16); -- sfix16_En15
  CONSTANT coeffphase9_11                 : signed(15 DOWNTO 0) := to_signed(-246, 16); -- sfix16_En15
  CONSTANT coeffphase9_12                 : signed(15 DOWNTO 0) := to_signed(176, 16); -- sfix16_En15
  CONSTANT coeffphase9_13                 : signed(15 DOWNTO 0) := to_signed(82, 16); -- sfix16_En15
  CONSTANT coeffphase9_14                 : signed(15 DOWNTO 0) := to_signed(-67, 16); -- sfix16_En15
  CONSTANT coeffphase9_15                 : signed(15 DOWNTO 0) := to_signed(-41, 16); -- sfix16_En15
  CONSTANT coeffphase9_16                 : signed(15 DOWNTO 0) := to_signed(35, 16); -- sfix16_En15
  CONSTANT coeffphase9_17                 : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase10_1                 : signed(15 DOWNTO 0) := to_signed(44, 16); -- sfix16_En15
  CONSTANT coeffphase10_2                 : signed(15 DOWNTO 0) := to_signed(-27, 16); -- sfix16_En15
  CONSTANT coeffphase10_3                 : signed(15 DOWNTO 0) := to_signed(-85, 16); -- sfix16_En15
  CONSTANT coeffphase10_4                 : signed(15 DOWNTO 0) := to_signed(54, 16); -- sfix16_En15
  CONSTANT coeffphase10_5                 : signed(15 DOWNTO 0) := to_signed(224, 16); -- sfix16_En15
  CONSTANT coeffphase10_6                 : signed(15 DOWNTO 0) := to_signed(-156, 16); -- sfix16_En15
  CONSTANT coeffphase10_7                 : signed(15 DOWNTO 0) := to_signed(-1652, 16); -- sfix16_En15
  CONSTANT coeffphase10_8                 : signed(15 DOWNTO 0) := to_signed(11287, 16); -- sfix16_En15
  CONSTANT coeffphase10_9                 : signed(15 DOWNTO 0) := to_signed(7649, 16); -- sfix16_En15
  CONSTANT coeffphase10_10                : signed(15 DOWNTO 0) := to_signed(-802, 16); -- sfix16_En15
  CONSTANT coeffphase10_11                : signed(15 DOWNTO 0) := to_signed(-302, 16); -- sfix16_En15
  CONSTANT coeffphase10_12                : signed(15 DOWNTO 0) := to_signed(117, 16); -- sfix16_En15
  CONSTANT coeffphase10_13                : signed(15 DOWNTO 0) := to_signed(101, 16); -- sfix16_En15
  CONSTANT coeffphase10_14                : signed(15 DOWNTO 0) := to_signed(-45, 16); -- sfix16_En15
  CONSTANT coeffphase10_15                : signed(15 DOWNTO 0) := to_signed(-50, 16); -- sfix16_En15
  CONSTANT coeffphase10_16                : signed(15 DOWNTO 0) := to_signed(24, 16); -- sfix16_En15
  CONSTANT coeffphase10_17                : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase11_1                 : signed(15 DOWNTO 0) := to_signed(50, 16); -- sfix16_En15
  CONSTANT coeffphase11_2                 : signed(15 DOWNTO 0) := to_signed(-10, 16); -- sfix16_En15
  CONSTANT coeffphase11_3                 : signed(15 DOWNTO 0) := to_signed(-96, 16); -- sfix16_En15
  CONSTANT coeffphase11_4                 : signed(15 DOWNTO 0) := to_signed(18, 16); -- sfix16_En15
  CONSTANT coeffphase11_5                 : signed(15 DOWNTO 0) := to_signed(258, 16); -- sfix16_En15
  CONSTANT coeffphase11_6                 : signed(15 DOWNTO 0) := to_signed(-38, 16); -- sfix16_En15
  CONSTANT coeffphase11_7                 : signed(15 DOWNTO 0) := to_signed(-2039, 16); -- sfix16_En15
  CONSTANT coeffphase11_8                 : signed(15 DOWNTO 0) := to_signed(13009, 16); -- sfix16_En15
  CONSTANT coeffphase11_9                 : signed(15 DOWNTO 0) := to_signed(5852, 16); -- sfix16_En15
  CONSTANT coeffphase11_10                : signed(15 DOWNTO 0) := to_signed(-399, 16); -- sfix16_En15
  CONSTANT coeffphase11_11                : signed(15 DOWNTO 0) := to_signed(-323, 16); -- sfix16_En15
  CONSTANT coeffphase11_12                : signed(15 DOWNTO 0) := to_signed(55, 16); -- sfix16_En15
  CONSTANT coeffphase11_13                : signed(15 DOWNTO 0) := to_signed(110, 16); -- sfix16_En15
  CONSTANT coeffphase11_14                : signed(15 DOWNTO 0) := to_signed(-20, 16); -- sfix16_En15
  CONSTANT coeffphase11_15                : signed(15 DOWNTO 0) := to_signed(-55, 16); -- sfix16_En15
  CONSTANT coeffphase11_16                : signed(15 DOWNTO 0) := to_signed(10, 16); -- sfix16_En15
  CONSTANT coeffphase11_17                : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase12_1                 : signed(15 DOWNTO 0) := to_signed(52, 16); -- sfix16_En15
  CONSTANT coeffphase12_2                 : signed(15 DOWNTO 0) := to_signed(9, 16); -- sfix16_En15
  CONSTANT coeffphase12_3                 : signed(15 DOWNTO 0) := to_signed(-101, 16); -- sfix16_En15
  CONSTANT coeffphase12_4                 : signed(15 DOWNTO 0) := to_signed(-22, 16); -- sfix16_En15
  CONSTANT coeffphase12_5                 : signed(15 DOWNTO 0) := to_signed(274, 16); -- sfix16_En15
  CONSTANT coeffphase12_6                 : signed(15 DOWNTO 0) := to_signed(102, 16); -- sfix16_En15
  CONSTANT coeffphase12_7                 : signed(15 DOWNTO 0) := to_signed(-2357, 16); -- sfix16_En15
  CONSTANT coeffphase12_8                 : signed(15 DOWNTO 0) := to_signed(14588, 16); -- sfix16_En15
  CONSTANT coeffphase12_9                 : signed(15 DOWNTO 0) := to_signed(4143, 16); -- sfix16_En15
  CONSTANT coeffphase12_10                : signed(15 DOWNTO 0) := to_signed(-42, 16); -- sfix16_En15
  CONSTANT coeffphase12_11                : signed(15 DOWNTO 0) := to_signed(-311, 16); -- sfix16_En15
  CONSTANT coeffphase12_12                : signed(15 DOWNTO 0) := to_signed(-7, 16); -- sfix16_En15
  CONSTANT coeffphase12_13                : signed(15 DOWNTO 0) := to_signed(108, 16); -- sfix16_En15
  CONSTANT coeffphase12_14                : signed(15 DOWNTO 0) := to_signed(5, 16); -- sfix16_En15
  CONSTANT coeffphase12_15                : signed(15 DOWNTO 0) := to_signed(-54, 16); -- sfix16_En15
  CONSTANT coeffphase12_16                : signed(15 DOWNTO 0) := to_signed(-3, 16); -- sfix16_En15
  CONSTANT coeffphase12_17                : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase13_1                 : signed(15 DOWNTO 0) := to_signed(49, 16); -- sfix16_En15
  CONSTANT coeffphase13_2                 : signed(15 DOWNTO 0) := to_signed(28, 16); -- sfix16_En15
  CONSTANT coeffphase13_3                 : signed(15 DOWNTO 0) := to_signed(-97, 16); -- sfix16_En15
  CONSTANT coeffphase13_4                 : signed(15 DOWNTO 0) := to_signed(-63, 16); -- sfix16_En15
  CONSTANT coeffphase13_5                 : signed(15 DOWNTO 0) := to_signed(270, 16); -- sfix16_En15
  CONSTANT coeffphase13_6                 : signed(15 DOWNTO 0) := to_signed(253, 16); -- sfix16_En15
  CONSTANT coeffphase13_7                 : signed(15 DOWNTO 0) := to_signed(-2570, 16); -- sfix16_En15
  CONSTANT coeffphase13_8                 : signed(15 DOWNTO 0) := to_signed(15966, 16); -- sfix16_En15
  CONSTANT coeffphase13_9                 : signed(15 DOWNTO 0) := to_signed(2570, 16); -- sfix16_En15
  CONSTANT coeffphase13_10                : signed(15 DOWNTO 0) := to_signed(253, 16); -- sfix16_En15
  CONSTANT coeffphase13_11                : signed(15 DOWNTO 0) := to_signed(-270, 16); -- sfix16_En15
  CONSTANT coeffphase13_12                : signed(15 DOWNTO 0) := to_signed(-63, 16); -- sfix16_En15
  CONSTANT coeffphase13_13                : signed(15 DOWNTO 0) := to_signed(97, 16); -- sfix16_En15
  CONSTANT coeffphase13_14                : signed(15 DOWNTO 0) := to_signed(28, 16); -- sfix16_En15
  CONSTANT coeffphase13_15                : signed(15 DOWNTO 0) := to_signed(-49, 16); -- sfix16_En15
  CONSTANT coeffphase13_16                : signed(15 DOWNTO 0) := to_signed(-16, 16); -- sfix16_En15
  CONSTANT coeffphase13_17                : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase14_1                 : signed(15 DOWNTO 0) := to_signed(43, 16); -- sfix16_En15
  CONSTANT coeffphase14_2                 : signed(15 DOWNTO 0) := to_signed(45, 16); -- sfix16_En15
  CONSTANT coeffphase14_3                 : signed(15 DOWNTO 0) := to_signed(-85, 16); -- sfix16_En15
  CONSTANT coeffphase14_4                 : signed(15 DOWNTO 0) := to_signed(-101, 16); -- sfix16_En15
  CONSTANT coeffphase14_5                 : signed(15 DOWNTO 0) := to_signed(243, 16); -- sfix16_En15
  CONSTANT coeffphase14_6                 : signed(15 DOWNTO 0) := to_signed(403, 16); -- sfix16_En15
  CONSTANT coeffphase14_7                 : signed(15 DOWNTO 0) := to_signed(-2643, 16); -- sfix16_En15
  CONSTANT coeffphase14_8                 : signed(15 DOWNTO 0) := to_signed(17095, 16); -- sfix16_En15
  CONSTANT coeffphase14_9                 : signed(15 DOWNTO 0) := to_signed(1171, 16); -- sfix16_En15
  CONSTANT coeffphase14_10                : signed(15 DOWNTO 0) := to_signed(476, 16); -- sfix16_En15
  CONSTANT coeffphase14_11                : signed(15 DOWNTO 0) := to_signed(-205, 16); -- sfix16_En15
  CONSTANT coeffphase14_12                : signed(15 DOWNTO 0) := to_signed(-109, 16); -- sfix16_En15
  CONSTANT coeffphase14_13                : signed(15 DOWNTO 0) := to_signed(77, 16); -- sfix16_En15
  CONSTANT coeffphase14_14                : signed(15 DOWNTO 0) := to_signed(47, 16); -- sfix16_En15
  CONSTANT coeffphase14_15                : signed(15 DOWNTO 0) := to_signed(-40, 16); -- sfix16_En15
  CONSTANT coeffphase14_16                : signed(15 DOWNTO 0) := to_signed(-26, 16); -- sfix16_En15
  CONSTANT coeffphase14_17                : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase15_1                 : signed(15 DOWNTO 0) := to_signed(32, 16); -- sfix16_En15
  CONSTANT coeffphase15_2                 : signed(15 DOWNTO 0) := to_signed(59, 16); -- sfix16_En15
  CONSTANT coeffphase15_3                 : signed(15 DOWNTO 0) := to_signed(-65, 16); -- sfix16_En15
  CONSTANT coeffphase15_4                 : signed(15 DOWNTO 0) := to_signed(-133, 16); -- sfix16_En15
  CONSTANT coeffphase15_5                 : signed(15 DOWNTO 0) := to_signed(195, 16); -- sfix16_En15
  CONSTANT coeffphase15_6                 : signed(15 DOWNTO 0) := to_signed(536, 16); -- sfix16_En15
  CONSTANT coeffphase15_7                 : signed(15 DOWNTO 0) := to_signed(-2546, 16); -- sfix16_En15
  CONSTANT coeffphase15_8                 : signed(15 DOWNTO 0) := to_signed(17933, 16); -- sfix16_En15
  CONSTANT coeffphase15_9                 : signed(15 DOWNTO 0) := to_signed(-25, 16); -- sfix16_En15
  CONSTANT coeffphase15_10                : signed(15 DOWNTO 0) := to_signed(622, 16); -- sfix16_En15
  CONSTANT coeffphase15_11                : signed(15 DOWNTO 0) := to_signed(-125, 16); -- sfix16_En15
  CONSTANT coeffphase15_12                : signed(15 DOWNTO 0) := to_signed(-142, 16); -- sfix16_En15
  CONSTANT coeffphase15_13                : signed(15 DOWNTO 0) := to_signed(50, 16); -- sfix16_En15
  CONSTANT coeffphase15_14                : signed(15 DOWNTO 0) := to_signed(62, 16); -- sfix16_En15
  CONSTANT coeffphase15_15                : signed(15 DOWNTO 0) := to_signed(-27, 16); -- sfix16_En15
  CONSTANT coeffphase15_16                : signed(15 DOWNTO 0) := to_signed(-35, 16); -- sfix16_En15
  CONSTANT coeffphase15_17                : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15
  CONSTANT coeffphase16_1                 : signed(15 DOWNTO 0) := to_signed(19, 16); -- sfix16_En15
  CONSTANT coeffphase16_2                 : signed(15 DOWNTO 0) := to_signed(69, 16); -- sfix16_En15
  CONSTANT coeffphase16_3                 : signed(15 DOWNTO 0) := to_signed(-40, 16); -- sfix16_En15
  CONSTANT coeffphase16_4                 : signed(15 DOWNTO 0) := to_signed(-155, 16); -- sfix16_En15
  CONSTANT coeffphase16_5                 : signed(15 DOWNTO 0) := to_signed(129, 16); -- sfix16_En15
  CONSTANT coeffphase16_6                 : signed(15 DOWNTO 0) := to_signed(639, 16); -- sfix16_En15
  CONSTANT coeffphase16_7                 : signed(15 DOWNTO 0) := to_signed(-2251, 16); -- sfix16_En15
  CONSTANT coeffphase16_8                 : signed(15 DOWNTO 0) := to_signed(18449, 16); -- sfix16_En15
  CONSTANT coeffphase16_9                 : signed(15 DOWNTO 0) := to_signed(-997, 16); -- sfix16_En15
  CONSTANT coeffphase16_10                : signed(15 DOWNTO 0) := to_signed(693, 16); -- sfix16_En15
  CONSTANT coeffphase16_11                : signed(15 DOWNTO 0) := to_signed(-38, 16); -- sfix16_En15
  CONSTANT coeffphase16_12                : signed(15 DOWNTO 0) := to_signed(-161, 16); -- sfix16_En15
  CONSTANT coeffphase16_13                : signed(15 DOWNTO 0) := to_signed(20, 16); -- sfix16_En15
  CONSTANT coeffphase16_14                : signed(15 DOWNTO 0) := to_signed(71, 16); -- sfix16_En15
  CONSTANT coeffphase16_15                : signed(15 DOWNTO 0) := to_signed(-12, 16); -- sfix16_En15
  CONSTANT coeffphase16_16                : signed(15 DOWNTO 0) := to_signed(-40, 16); -- sfix16_En15
  CONSTANT coeffphase16_17                : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En15

  -- Signals
  SIGNAL cur_count                        : unsigned(3 DOWNTO 0); -- ufix4
  SIGNAL phase_15                         : std_logic; -- boolean
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 15); -- sfix16_En15
  SIGNAL PN_genera_ip_src_FIR_Interpolation_in_regtype : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product                          : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux                      : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_1                        : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_1                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_2                        : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_2                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_3                        : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_3                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_4                        : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_4                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_5                        : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_5                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_6                        : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_6                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_7                        : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_7                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_8                        : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_8                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_9                        : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_9                    : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_10                       : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_10                   : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_11                       : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_11                   : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_12                       : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_12                   : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_13                       : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_13                   : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_14                       : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_14                   : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_15                       : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_15                   : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL product_16                       : signed(31 DOWNTO 0); -- sfix32_En30
  SIGNAL product_mux_16                   : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL sum1                             : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast                         : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_1                       : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp                         : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum2                             : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_2                       : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_3                       : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_1                       : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum3                             : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_4                       : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_5                       : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_2                       : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum4                             : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_6                       : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_7                       : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_3                       : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum5                             : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_8                       : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_9                       : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_4                       : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum6                             : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_10                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_11                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_5                       : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum7                             : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_12                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_13                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_6                       : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum8                             : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_14                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_15                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_7                       : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum9                             : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_16                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_17                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_8                       : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum10                            : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_18                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_19                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_9                       : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum11                            : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_20                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_21                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_10                      : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum12                            : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_22                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_23                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_11                      : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum13                            : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_24                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_25                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_12                      : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum14                            : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_26                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_27                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_13                      : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum15                            : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_28                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_29                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_14                      : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL sum16                            : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_30                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_cast_31                      : signed(36 DOWNTO 0); -- sfix37_En30
  SIGNAL add_temp_15                      : signed(37 DOWNTO 0); -- sfix38_En30
  SIGNAL output_typeconvert               : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL regout                           : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL muxout                           : signed(15 DOWNTO 0); -- sfix16_En15


BEGIN

  -- Block Statements
  ce_output : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      cur_count <= to_unsigned(0, 4);
    ELSIF clk'event AND clk = '1' THEN
      IF enb_1_1_1 = '1' THEN
        IF cur_count >= to_unsigned(15, 4) THEN
          cur_count <= to_unsigned(0, 4);
        ELSE
          cur_count <= cur_count + to_unsigned(1, 4);
        END IF;
      END IF;
    END IF; 
  END PROCESS ce_output;

  phase_15 <= '1' WHEN cur_count = to_unsigned(15, 4) AND enb_1_1_1 = '1' ELSE '0';

  --   ---------------- Delay Registers ----------------

  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 15) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF phase_15 = '1' THEN
        delay_pipeline(0) <= signed(PN_genera_ip_src_FIR_Interpolation_in);
        delay_pipeline(1 TO 15) <= delay_pipeline(0 TO 14);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  PN_genera_ip_src_FIR_Interpolation_in_regtype <= signed(PN_genera_ip_src_FIR_Interpolation_in);

  product_mux <= coeffphase1_17 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                      coeffphase2_17 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                      coeffphase3_17 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                      coeffphase4_17 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                      coeffphase5_17 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                      coeffphase6_17 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                      coeffphase7_17 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                      coeffphase8_17 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                      coeffphase9_17 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                      coeffphase10_17 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                      coeffphase11_17 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                      coeffphase12_17 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                      coeffphase13_17 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                      coeffphase14_17 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                      coeffphase15_17 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                      coeffphase16_17;
  product <= delay_pipeline(15) * product_mux;

  product_mux_1 <= coeffphase1_16 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                        coeffphase2_16 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                        coeffphase3_16 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                        coeffphase4_16 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                        coeffphase5_16 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                        coeffphase6_16 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                        coeffphase7_16 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                        coeffphase8_16 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                        coeffphase9_16 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                        coeffphase10_16 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                        coeffphase11_16 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                        coeffphase12_16 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                        coeffphase13_16 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                        coeffphase14_16 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                        coeffphase15_16 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                        coeffphase16_16;
  product_1 <= delay_pipeline(14) * product_mux_1;

  product_mux_2 <= coeffphase1_15 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                        coeffphase2_15 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                        coeffphase3_15 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                        coeffphase4_15 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                        coeffphase5_15 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                        coeffphase6_15 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                        coeffphase7_15 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                        coeffphase8_15 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                        coeffphase9_15 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                        coeffphase10_15 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                        coeffphase11_15 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                        coeffphase12_15 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                        coeffphase13_15 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                        coeffphase14_15 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                        coeffphase15_15 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                        coeffphase16_15;
  product_2 <= delay_pipeline(13) * product_mux_2;

  product_mux_3 <= coeffphase1_14 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                        coeffphase2_14 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                        coeffphase3_14 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                        coeffphase4_14 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                        coeffphase5_14 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                        coeffphase6_14 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                        coeffphase7_14 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                        coeffphase8_14 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                        coeffphase9_14 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                        coeffphase10_14 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                        coeffphase11_14 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                        coeffphase12_14 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                        coeffphase13_14 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                        coeffphase14_14 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                        coeffphase15_14 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                        coeffphase16_14;
  product_3 <= delay_pipeline(12) * product_mux_3;

  product_mux_4 <= coeffphase1_13 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                        coeffphase2_13 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                        coeffphase3_13 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                        coeffphase4_13 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                        coeffphase5_13 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                        coeffphase6_13 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                        coeffphase7_13 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                        coeffphase8_13 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                        coeffphase9_13 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                        coeffphase10_13 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                        coeffphase11_13 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                        coeffphase12_13 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                        coeffphase13_13 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                        coeffphase14_13 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                        coeffphase15_13 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                        coeffphase16_13;
  product_4 <= delay_pipeline(11) * product_mux_4;

  product_mux_5 <= coeffphase1_12 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                        coeffphase2_12 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                        coeffphase3_12 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                        coeffphase4_12 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                        coeffphase5_12 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                        coeffphase6_12 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                        coeffphase7_12 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                        coeffphase8_12 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                        coeffphase9_12 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                        coeffphase10_12 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                        coeffphase11_12 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                        coeffphase12_12 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                        coeffphase13_12 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                        coeffphase14_12 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                        coeffphase15_12 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                        coeffphase16_12;
  product_5 <= delay_pipeline(10) * product_mux_5;

  product_mux_6 <= coeffphase1_11 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                        coeffphase2_11 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                        coeffphase3_11 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                        coeffphase4_11 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                        coeffphase5_11 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                        coeffphase6_11 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                        coeffphase7_11 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                        coeffphase8_11 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                        coeffphase9_11 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                        coeffphase10_11 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                        coeffphase11_11 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                        coeffphase12_11 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                        coeffphase13_11 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                        coeffphase14_11 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                        coeffphase15_11 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                        coeffphase16_11;
  product_6 <= delay_pipeline(9) * product_mux_6;

  product_mux_7 <= coeffphase1_10 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                        coeffphase2_10 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                        coeffphase3_10 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                        coeffphase4_10 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                        coeffphase5_10 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                        coeffphase6_10 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                        coeffphase7_10 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                        coeffphase8_10 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                        coeffphase9_10 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                        coeffphase10_10 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                        coeffphase11_10 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                        coeffphase12_10 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                        coeffphase13_10 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                        coeffphase14_10 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                        coeffphase15_10 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                        coeffphase16_10;
  product_7 <= delay_pipeline(8) * product_mux_7;

  product_mux_8 <= coeffphase1_9 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                        coeffphase2_9 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                        coeffphase3_9 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                        coeffphase4_9 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                        coeffphase5_9 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                        coeffphase6_9 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                        coeffphase7_9 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                        coeffphase8_9 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                        coeffphase9_9 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                        coeffphase10_9 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                        coeffphase11_9 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                        coeffphase12_9 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                        coeffphase13_9 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                        coeffphase14_9 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                        coeffphase15_9 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                        coeffphase16_9;
  product_8 <= delay_pipeline(7) * product_mux_8;

  product_mux_9 <= coeffphase1_8 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                        coeffphase2_8 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                        coeffphase3_8 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                        coeffphase4_8 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                        coeffphase5_8 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                        coeffphase6_8 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                        coeffphase7_8 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                        coeffphase8_8 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                        coeffphase9_8 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                        coeffphase10_8 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                        coeffphase11_8 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                        coeffphase12_8 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                        coeffphase13_8 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                        coeffphase14_8 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                        coeffphase15_8 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                        coeffphase16_8;
  product_9 <= delay_pipeline(6) * product_mux_9;

  product_mux_10 <= coeffphase1_7 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                         coeffphase2_7 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                         coeffphase3_7 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                         coeffphase4_7 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                         coeffphase5_7 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                         coeffphase6_7 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                         coeffphase7_7 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                         coeffphase8_7 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                         coeffphase9_7 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                         coeffphase10_7 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                         coeffphase11_7 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                         coeffphase12_7 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                         coeffphase13_7 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                         coeffphase14_7 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                         coeffphase15_7 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                         coeffphase16_7;
  product_10 <= delay_pipeline(5) * product_mux_10;

  product_mux_11 <= coeffphase1_6 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                         coeffphase2_6 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                         coeffphase3_6 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                         coeffphase4_6 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                         coeffphase5_6 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                         coeffphase6_6 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                         coeffphase7_6 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                         coeffphase8_6 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                         coeffphase9_6 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                         coeffphase10_6 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                         coeffphase11_6 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                         coeffphase12_6 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                         coeffphase13_6 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                         coeffphase14_6 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                         coeffphase15_6 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                         coeffphase16_6;
  product_11 <= delay_pipeline(4) * product_mux_11;

  product_mux_12 <= coeffphase1_5 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                         coeffphase2_5 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                         coeffphase3_5 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                         coeffphase4_5 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                         coeffphase5_5 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                         coeffphase6_5 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                         coeffphase7_5 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                         coeffphase8_5 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                         coeffphase9_5 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                         coeffphase10_5 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                         coeffphase11_5 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                         coeffphase12_5 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                         coeffphase13_5 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                         coeffphase14_5 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                         coeffphase15_5 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                         coeffphase16_5;
  product_12 <= delay_pipeline(3) * product_mux_12;

  product_mux_13 <= coeffphase1_4 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                         coeffphase2_4 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                         coeffphase3_4 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                         coeffphase4_4 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                         coeffphase5_4 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                         coeffphase6_4 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                         coeffphase7_4 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                         coeffphase8_4 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                         coeffphase9_4 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                         coeffphase10_4 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                         coeffphase11_4 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                         coeffphase12_4 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                         coeffphase13_4 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                         coeffphase14_4 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                         coeffphase15_4 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                         coeffphase16_4;
  product_13 <= delay_pipeline(2) * product_mux_13;

  product_mux_14 <= coeffphase1_3 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                         coeffphase2_3 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                         coeffphase3_3 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                         coeffphase4_3 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                         coeffphase5_3 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                         coeffphase6_3 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                         coeffphase7_3 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                         coeffphase8_3 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                         coeffphase9_3 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                         coeffphase10_3 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                         coeffphase11_3 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                         coeffphase12_3 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                         coeffphase13_3 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                         coeffphase14_3 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                         coeffphase15_3 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                         coeffphase16_3;
  product_14 <= delay_pipeline(1) * product_mux_14;

  product_mux_15 <= coeffphase1_2 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                         coeffphase2_2 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                         coeffphase3_2 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                         coeffphase4_2 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                         coeffphase5_2 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                         coeffphase6_2 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                         coeffphase7_2 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                         coeffphase8_2 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                         coeffphase9_2 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                         coeffphase10_2 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                         coeffphase11_2 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                         coeffphase12_2 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                         coeffphase13_2 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                         coeffphase14_2 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                         coeffphase15_2 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                         coeffphase16_2;
  product_15 <= delay_pipeline(0) * product_mux_15;

  product_mux_16 <= coeffphase1_1 WHEN ( cur_count = to_unsigned(0, 4) ) ELSE
                         coeffphase2_1 WHEN ( cur_count = to_unsigned(1, 4) ) ELSE
                         coeffphase3_1 WHEN ( cur_count = to_unsigned(2, 4) ) ELSE
                         coeffphase4_1 WHEN ( cur_count = to_unsigned(3, 4) ) ELSE
                         coeffphase5_1 WHEN ( cur_count = to_unsigned(4, 4) ) ELSE
                         coeffphase6_1 WHEN ( cur_count = to_unsigned(5, 4) ) ELSE
                         coeffphase7_1 WHEN ( cur_count = to_unsigned(6, 4) ) ELSE
                         coeffphase8_1 WHEN ( cur_count = to_unsigned(7, 4) ) ELSE
                         coeffphase9_1 WHEN ( cur_count = to_unsigned(8, 4) ) ELSE
                         coeffphase10_1 WHEN ( cur_count = to_unsigned(9, 4) ) ELSE
                         coeffphase11_1 WHEN ( cur_count = to_unsigned(10, 4) ) ELSE
                         coeffphase12_1 WHEN ( cur_count = to_unsigned(11, 4) ) ELSE
                         coeffphase13_1 WHEN ( cur_count = to_unsigned(12, 4) ) ELSE
                         coeffphase14_1 WHEN ( cur_count = to_unsigned(13, 4) ) ELSE
                         coeffphase15_1 WHEN ( cur_count = to_unsigned(14, 4) ) ELSE
                         coeffphase16_1;
  product_16 <= PN_genera_ip_src_FIR_Interpolation_in_regtype * product_mux_16;

  add_cast <= resize(product_16, 37);
  add_cast_1 <= resize(product_15, 37);
  add_temp <= resize(add_cast, 38) + resize(add_cast_1, 38);
  sum1 <= add_temp(36 DOWNTO 0);

  add_cast_2 <= sum1;
  add_cast_3 <= resize(product_14, 37);
  add_temp_1 <= resize(add_cast_2, 38) + resize(add_cast_3, 38);
  sum2 <= add_temp_1(36 DOWNTO 0);

  add_cast_4 <= sum2;
  add_cast_5 <= resize(product_13, 37);
  add_temp_2 <= resize(add_cast_4, 38) + resize(add_cast_5, 38);
  sum3 <= add_temp_2(36 DOWNTO 0);

  add_cast_6 <= sum3;
  add_cast_7 <= resize(product_12, 37);
  add_temp_3 <= resize(add_cast_6, 38) + resize(add_cast_7, 38);
  sum4 <= add_temp_3(36 DOWNTO 0);

  add_cast_8 <= sum4;
  add_cast_9 <= resize(product_11, 37);
  add_temp_4 <= resize(add_cast_8, 38) + resize(add_cast_9, 38);
  sum5 <= add_temp_4(36 DOWNTO 0);

  add_cast_10 <= sum5;
  add_cast_11 <= resize(product_10, 37);
  add_temp_5 <= resize(add_cast_10, 38) + resize(add_cast_11, 38);
  sum6 <= add_temp_5(36 DOWNTO 0);

  add_cast_12 <= sum6;
  add_cast_13 <= resize(product_9, 37);
  add_temp_6 <= resize(add_cast_12, 38) + resize(add_cast_13, 38);
  sum7 <= add_temp_6(36 DOWNTO 0);

  add_cast_14 <= sum7;
  add_cast_15 <= resize(product_8, 37);
  add_temp_7 <= resize(add_cast_14, 38) + resize(add_cast_15, 38);
  sum8 <= add_temp_7(36 DOWNTO 0);

  add_cast_16 <= sum8;
  add_cast_17 <= resize(product_7, 37);
  add_temp_8 <= resize(add_cast_16, 38) + resize(add_cast_17, 38);
  sum9 <= add_temp_8(36 DOWNTO 0);

  add_cast_18 <= sum9;
  add_cast_19 <= resize(product_6, 37);
  add_temp_9 <= resize(add_cast_18, 38) + resize(add_cast_19, 38);
  sum10 <= add_temp_9(36 DOWNTO 0);

  add_cast_20 <= sum10;
  add_cast_21 <= resize(product_5, 37);
  add_temp_10 <= resize(add_cast_20, 38) + resize(add_cast_21, 38);
  sum11 <= add_temp_10(36 DOWNTO 0);

  add_cast_22 <= sum11;
  add_cast_23 <= resize(product_4, 37);
  add_temp_11 <= resize(add_cast_22, 38) + resize(add_cast_23, 38);
  sum12 <= add_temp_11(36 DOWNTO 0);

  add_cast_24 <= sum12;
  add_cast_25 <= resize(product_3, 37);
  add_temp_12 <= resize(add_cast_24, 38) + resize(add_cast_25, 38);
  sum13 <= add_temp_12(36 DOWNTO 0);

  add_cast_26 <= sum13;
  add_cast_27 <= resize(product_2, 37);
  add_temp_13 <= resize(add_cast_26, 38) + resize(add_cast_27, 38);
  sum14 <= add_temp_13(36 DOWNTO 0);

  add_cast_28 <= sum14;
  add_cast_29 <= resize(product_1, 37);
  add_temp_14 <= resize(add_cast_28, 38) + resize(add_cast_29, 38);
  sum15 <= add_temp_14(36 DOWNTO 0);

  add_cast_30 <= sum15;
  add_cast_31 <= resize(product, 37);
  add_temp_15 <= resize(add_cast_30, 38) + resize(add_cast_31, 38);
  sum16 <= add_temp_15(36 DOWNTO 0);

  output_typeconvert <= sum16(30 DOWNTO 15);

  DataHoldRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      regout <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF enb_1_1_1 = '1' THEN
        regout <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS DataHoldRegister_process;

  muxout <= output_typeconvert WHEN ( enb_1_1_1 = '1' ) ELSE
            regout;
  -- Assignment Statements
  PN_genera_ip_src_FIR_Interpolation_out <= std_logic_vector(muxout);
END rtl;
