SLStudio.Utils.RemoveHighlighting(get_param('PN_generatorV2', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_PN_generatorV2', 'handle'));
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter', 0, 1, '');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter', 1, 1, '');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter', 1, 1, '');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter1', 1, 1, '');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter1', 1, 1, '');
annotate_port('gm_PN_generatorV2/Receptor/BPSK Demodulator Baseband', 0, 1, '');
annotate_port('gm_PN_generatorV2/Receptor/BPSK Demodulator Baseband', 1, 1, '');
annotate_port('PN_generatorV2/Receptor/BPSK Demodulator Baseband', 1, 1, '');
annotate_port('gm_PN_generatorV2/Receptor/BPSK Demodulator Baseband', 1, 1, '');
annotate_port('PN_generatorV2/Receptor/BPSK Demodulator Baseband', 1, 1, '');
annotate_port('gm_PN_generatorV2/Receptor/Data Type Conversion', 0, 1, '');
annotate_port('gm_PN_generatorV2/Receptor/Real-Imag to Complex', 0, 1, '');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 0, 1, '');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 1, 1, '');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 1, 1, '');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 1, 1, '');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 1, 1, '');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 1, 1, '');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 1, 1, '');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 1, 1, '');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 1, 1, '');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 1, 1, '');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 1, 1, '');
