open_system('gm_PN_generatorV2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter', 'user2');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/BPSK Demodulator Baseband', 'user2');
annotate_port('gm_PN_generatorV2/Receptor/BPSK Demodulator Baseband', 0, 1, 'cp : 0.9185 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/Data Type Conversion', 'user1');
annotate_port('gm_PN_generatorV2/Receptor/Data Type Conversion', 0, 1, 'cp : 0.9185 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/Real-Imag to Complex', 'user2');
annotate_port('gm_PN_generatorV2/Receptor/Real-Imag to Complex', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 'user2');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 0, 1, 'cp : 0 ns');
