open_system('PN_generatorV2');
open_system('gm_PN_generatorV2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter', 'user2');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Receptor/Raised Cosine Receive Filter', 'user2');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter1', 'user2');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter1', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Receptor/Raised Cosine Receive Filter1', 'user2');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/BPSK Demodulator Baseband', 'user2');
annotate_port('gm_PN_generatorV2/Receptor/BPSK Demodulator Baseband', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Receptor/BPSK Demodulator Baseband', 'user2');
annotate_port('PN_generatorV2/Receptor/BPSK Demodulator Baseband', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/BPSK Demodulator Baseband', 'user2');
annotate_port('gm_PN_generatorV2/Receptor/BPSK Demodulator Baseband', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Receptor/BPSK Demodulator Baseband', 'user2');
annotate_port('PN_generatorV2/Receptor/BPSK Demodulator Baseband', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 'user2');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 'user2');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 'user2');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 'user2');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 'user2');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 'user2');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 'user2');
annotate_port('gm_PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 'user2');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 'user2');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter/FIR Decimation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 'user2');
annotate_port('PN_generatorV2/Receptor/Raised Cosine Receive Filter1/FIR Decimation', 1, 1, 'Block not characterized');
