-- -------------------------------------------------------------
-- 
-- File Name: PN_generator_RX\hdlsrc\PN_generatorV2\PN_genera_ip_src_Raised_Cosine_Receive_Filter1.vhd
-- Created: 2020-05-30 20:12:39
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PN_genera_ip_src_Raised_Cosine_Receive_Filter1
-- Source Path: PN_generatorV2/Receptor/Raised Cosine Receive Filter1
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PN_genera_ip_src_Raised_Cosine_Receive_Filter1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_1_1                         :   IN    std_logic;
        In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END PN_genera_ip_src_Raised_Cosine_Receive_Filter1;


ARCHITECTURE rtl OF PN_genera_ip_src_Raised_Cosine_Receive_Filter1 IS

  -- Component Declarations
  COMPONENT PN_genera_ip_src_FIR_Decimation_block
    PORT( clk                             :   IN    std_logic;
          enb_1_1_1                       :   IN    std_logic;
          reset                           :   IN    std_logic;
          PN_genera_ip_src_FIR_Decimation_block_in :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          PN_genera_ip_src_FIR_Decimation_block_out :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : PN_genera_ip_src_FIR_Decimation_block
    USE ENTITY work.PN_genera_ip_src_FIR_Decimation_block(rtl);

  -- Signals
  SIGNAL FIR_Decimation_out1              : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_PN_genera_ip_src_FIR_Decimation_block : PN_genera_ip_src_FIR_Decimation_block
    PORT MAP( clk => clk,
              enb_1_1_1 => enb_1_1_1,
              reset => reset,
              PN_genera_ip_src_FIR_Decimation_block_in => In1,  -- sfix16_En15
              PN_genera_ip_src_FIR_Decimation_block_out => FIR_Decimation_out1  -- sfix16_En15
              );

  Out1 <= FIR_Decimation_out1;

END rtl;

