-- -------------------------------------------------------------
-- 
-- File Name: PN_generator_RX\hdlsrc\PN_generatorV2\PN_genera_ip_src_BPSK_Demodulator_Baseband.vhd
-- Created: 2020-05-30 20:12:39
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PN_genera_ip_src_BPSK_Demodulator_Baseband
-- Source Path: PN_generatorV2/Receptor/BPSK Demodulator Baseband
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PN_genera_ip_src_BPSK_Demodulator_Baseband IS
  PORT( in0_re                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        in0_im                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        out0                              :   OUT   std_logic  -- ufix1
        );
END PN_genera_ip_src_BPSK_Demodulator_Baseband;


ARCHITECTURE rtl OF PN_genera_ip_src_BPSK_Demodulator_Baseband IS

  -- Constants
  CONSTANT DirectLookupTable_data         : std_logic_vector(0 TO 7) := 
    ('0', '0', '1', '0', '1', '1', '1', '0');  -- ufix1 [8]

  -- Signals
  SIGNAL in0_re_signed                    : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL in0_im_signed                    : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL inphase_lt_zero                  : std_logic;
  SIGNAL inphase_eq_zero                  : std_logic;
  SIGNAL quadrature_eq_zero               : std_logic;
  SIGNAL decisionLUTaddr                  : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL hardDecision                     : std_logic;  -- ufix1

BEGIN
  in0_re_signed <= signed(in0_re);

  
  inphase_lt_zero <= '1' WHEN in0_re_signed < to_signed(16#0000#, 16) ELSE
      '0';

  
  inphase_eq_zero <= '1' WHEN in0_re_signed = to_signed(16#0000#, 16) ELSE
      '0';

  in0_im_signed <= signed(in0_im);

  
  quadrature_eq_zero <= '1' WHEN in0_im_signed = to_signed(16#0000#, 16) ELSE
      '0';

  decisionLUTaddr <= unsigned'(inphase_lt_zero & inphase_eq_zero & quadrature_eq_zero);

  hardDecision <= DirectLookupTable_data(to_integer(decisionLUTaddr));

  out0 <= hardDecision;

END rtl;

