SLStudio.Utils.RemoveHighlighting(get_param('PN_generatorV2', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_PN_generatorV2', 'handle'));
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator', 0, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator', 0, 1, '');
annotate_port('PN_generatorV2/Transmisor/Gold Sequence Generator', 0, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2', 1, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2', 1, 1, '');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2', 1, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3', 1, 1, '');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3', 1, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/BPSK Modulator Baseband', 0, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/BPSK Modulator Baseband', 1, 1, '');
annotate_port('PN_generatorV2/Transmisor/BPSK Modulator Baseband', 1, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/BPSK Modulator Baseband', 1, 1, '');
annotate_port('PN_generatorV2/Transmisor/BPSK Modulator Baseband', 1, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Complex to Real-Imag1', 0, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator1', 0, 1, '');
annotate_port('PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator1', 0, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator1', 0, 1, '');
annotate_port('PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator1', 0, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 0, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 0, 1, '');
annotate_port('PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 0, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 0, 1, '');
annotate_port('PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 0, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/Logical Operator', 0, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 1, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 1, 1, '');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 1, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 1, 1, '');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 1, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 1, 1, '');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 1, 1, '');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 1, 1, '');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 1, 1, '');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 1, 1, '');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 1, 1, '');
