open_system('gm_PN_generatorV2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Gold Sequence Generator', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator', 0, 1, 'cp : 2.762 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2', 1, 1, 'cp : 3.179 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/BPSK Modulator Baseband', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/BPSK Modulator Baseband', 0, 1, 'cp : 3.179 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Complex to Real-Imag1', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Complex to Real-Imag1', 0, 1, 'cp : 3.179 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 0, 1, 'cp : 1.779 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/Logical Operator', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/Logical Operator', 0, 1, 'cp : 2.762 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 1, 1, 'cp : 3.179 ns');
