open_system('PN_generatorV2');
open_system('gm_PN_generatorV2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Gold Sequence Generator', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator', 0, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/Gold Sequence Generator', 'user2');
annotate_port('PN_generatorV2/Transmisor/Gold Sequence Generator', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2', 'user2');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3', 'user2');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/BPSK Modulator Baseband', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/BPSK Modulator Baseband', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/BPSK Modulator Baseband', 'user2');
annotate_port('PN_generatorV2/Transmisor/BPSK Modulator Baseband', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/BPSK Modulator Baseband', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/BPSK Modulator Baseband', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/BPSK Modulator Baseband', 'user2');
annotate_port('PN_generatorV2/Transmisor/BPSK Modulator Baseband', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator1', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator1', 0, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator1', 'user2');
annotate_port('PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator1', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator1', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator1', 0, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator1', 'user2');
annotate_port('PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator1', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 0, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 'user2');
annotate_port('PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 0, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 'user2');
annotate_port('PN_generatorV2/Transmisor/Gold Sequence Generator/PN Sequence Generator2', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 'user2');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 'user2');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 'user2');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 'user2');
annotate_port('gm_PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 1, 1, 'Block not characterized');
hilite_system('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 'user2');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 'user2');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter2/FIR Interpolation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 'user2');
annotate_port('PN_generatorV2/Transmisor/Raised Cosine Transmit Filter3/FIR Interpolation', 1, 1, 'Block not characterized');
