-- -------------------------------------------------------------
-- 
-- File Name: PN_generator_TX\hdlsrc\PN_generatorV2\PN_genera_ip_tx_addr_decoder.vhd
-- Created: 2020-05-30 21:58:13
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PN_genera_ip_tx_addr_decoder
-- Source Path: PN_genera_ip_tx/PN_genera_ip_tx_axi_lite/PN_genera_ip_tx_addr_decoder
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PN_genera_ip_tx_addr_decoder IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        data_write                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        addr_sel                          :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        wr_enb                            :   IN    std_logic;  -- ufix1
        rd_enb                            :   IN    std_logic;  -- ufix1
        read_ip_timestamp                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        read_Original_code                :   IN    std_logic;  -- ufix1
        read_real                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        read_imaginary                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        data_read                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_axi_enable                  :   OUT   std_logic  -- ufix1
        );
END PN_genera_ip_tx_addr_decoder;


ARCHITECTURE rtl OF PN_genera_ip_tx_addr_decoder IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL addr_sel_unsigned                : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL decode_sel_ip_timestamp_1_1      : std_logic;  -- ufix1
  SIGNAL read_ip_timestamp_unsigned       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL const_1                          : std_logic;  -- ufix1
  SIGNAL read_real_signed                 : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL read_imaginary_signed            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL decode_sel_imaginary_1_1         : std_logic;  -- ufix1
  SIGNAL decode_sel_real_1_1              : std_logic;  -- ufix1
  SIGNAL decode_sel_Original_code_1_1     : std_logic;  -- ufix1
  SIGNAL const_0                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_ip_timestamp            : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_ip_timestamp_1_1       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_Original_code           : std_logic;  -- ufix1
  SIGNAL data_slice_Original_code_1       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_Original_code_1_1      : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_real                    : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL data_slice_real_1                : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_real_1_1               : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_imaginary               : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL data_slice_imaginary_1           : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_imaginary_1_1          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_axi_enable_1_1        : std_logic;  -- ufix1
  SIGNAL reg_enb_axi_enable_1_1           : std_logic;  -- ufix1
  SIGNAL data_write_unsigned              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL data_in_axi_enable               : std_logic;  -- ufix1
  SIGNAL data_reg_axi_enable_1_1          : std_logic;  -- ufix1
  SIGNAL write_concats_axi_enable_1       : std_logic;  -- ufix1

BEGIN
  addr_sel_unsigned <= unsigned(addr_sel);

  
  decode_sel_ip_timestamp_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0002#, 14) ELSE
      '0';

  read_ip_timestamp_unsigned <= unsigned(read_ip_timestamp);

  const_1 <= '1';

  enb <= const_1;

  read_real_signed <= signed(read_real);

  read_imaginary_signed <= signed(read_imaginary);

  
  decode_sel_imaginary_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0042#, 14) ELSE
      '0';

  
  decode_sel_real_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0041#, 14) ELSE
      '0';

  
  decode_sel_Original_code_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0040#, 14) ELSE
      '0';

  const_0 <= to_unsigned(0, 32);

  reg_ip_timestamp_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_ip_timestamp <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_ip_timestamp <= read_ip_timestamp_unsigned;
      END IF;
    END IF;
  END PROCESS reg_ip_timestamp_process;


  
  decode_rd_ip_timestamp_1_1 <= const_0 WHEN decode_sel_ip_timestamp_1_1 = '0' ELSE
      read_reg_ip_timestamp;

  reg_Original_code_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_Original_code <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_Original_code <= read_Original_code;
      END IF;
    END IF;
  END PROCESS reg_Original_code_process;


  data_slice_Original_code_1 <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & read_reg_Original_code;

  
  decode_rd_Original_code_1_1 <= decode_rd_ip_timestamp_1_1 WHEN decode_sel_Original_code_1_1 = '0' ELSE
      data_slice_Original_code_1;

  reg_real_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_real <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_real <= read_real_signed;
      END IF;
    END IF;
  END PROCESS reg_real_process;


  data_slice_real_1 <= unsigned(resize(read_reg_real, 32));

  
  decode_rd_real_1_1 <= decode_rd_Original_code_1_1 WHEN decode_sel_real_1_1 = '0' ELSE
      data_slice_real_1;

  reg_imaginary_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      read_reg_imaginary <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_imaginary <= read_imaginary_signed;
      END IF;
    END IF;
  END PROCESS reg_imaginary_process;


  data_slice_imaginary_1 <= unsigned(resize(read_reg_imaginary, 32));

  
  decode_rd_imaginary_1_1 <= decode_rd_real_1_1 WHEN decode_sel_imaginary_1_1 = '0' ELSE
      data_slice_imaginary_1;

  data_read <= std_logic_vector(decode_rd_imaginary_1_1);

  
  decode_sel_axi_enable_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0001#, 14) ELSE
      '0';

  reg_enb_axi_enable_1_1 <= decode_sel_axi_enable_1_1 AND wr_enb;

  data_write_unsigned <= unsigned(data_write);

  data_in_axi_enable <= data_write_unsigned(0);

  reg_axi_enable_1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_reg_axi_enable_1_1 <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_axi_enable_1_1 = '1' THEN
        data_reg_axi_enable_1_1 <= data_in_axi_enable;
      END IF;
    END IF;
  END PROCESS reg_axi_enable_1_1_process;


  write_concats_axi_enable_1 <= data_reg_axi_enable_1_1;

  write_axi_enable <= write_concats_axi_enable_1;

END rtl;

